version: "0.1"
services:
  db:
    container_name: peppermint-db
    image: postgres:15.1
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  app:
    container_name: peppermint-app
    entrypoint: ~/initial-startup.sh
    build:
      dockerfile: ./dockerfile
    ports:
      - "8000:8000"
      - "5173:5173"
    environment:
      - PYTHONPATH=/home/deploy/peppermint/backend
    volumes:
      - ./:/home/deploy/peppermint

volumes:
  db-data:
